version: "3"
services:
  coordinator:
    image: ochaloup/lra-coordinator:devconf2019
    expose:
      - 8080
  ruby-api:
    build:
      context: extra
    expose:
      - 4567
    ports:
      - 4567:4567
    volumes:
      - ./:/data:z
    command: |
      sh -c 'cd /data && ls -la /data && bundle install && bundle exec ruby app/api.rb'
  dynflow:
    build:
      context: extra
    expose:
      - 3000
    volumes:
      - ./:/data:z
    command: |
      sh -c 'cd /data && bundle install && bundle exec ruby app/dynflow.rb'
  lraservice:
    image: ochaloup/devconf2019:presentation
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - LRA_ENLIST_BASE_URI=http://lraservice:8080/
      - TARGET_CALL=http://ruby-api:4567/
    # command: curl -i -X POST -d '' http://ruby-api:4567/
